console.log('luckySnail use fs writeFile API !')
console.log('luckySnail use fs writeFile API !')
console.log('luckySnail use fs writeFile API !')
console.log('luckySnail use fs writeFile API !')
console.log('luckySnail use fs writeFile API !')